### ISSUE TITLE
Errors with get_unspents()

### ISSUE THREAD

**Issue by Gz75y45ms3kc** [pybitcash/bitcash#101]
I'm getting an error with get_unspents() roughly half the time. The problem seems to be that sometimes the BitcoinDotComAPI is called (which isn't working) and sometimes it's BitcoreAPI (which is). Can the BitcoinDotComAPI.get_unspent() method be removed from NetworkAPI?

**Comment by merc1er** [comment]
What version of BitCash are you running?

**Comment by merc1er** [comment]
`BitcoreAPI` is actually not working and being removed from the codebase. As for the main API, it is customisable and you can replace it with your own node if you find the public on unreliable (even though it has been reliable for me so far).

**Comment by Gz75y45ms3kc** [comment]
I'm using 0.6.3, the latest as far as I can tell. I was getting errors with get_unspent() for both mainnet and testnet yesterday. Testnet uses the trest.bitcoin.com API which is shutting down. I figured out how to call the BitcoreAPI.get_unspent() directly. Mainnet uses rest1.biggestfan.net which should be fine? I'm not getting any errors today, so I can close the issue.

What's wrong with BitcoreAPI? I'm not having any problems with it.

My own node would be nice. I don't think my university will pay for/manage it, unfortunately.

**Comment by merc1er** [comment]
> Mainnet uses rest1.biggestfan.net which should be fine? I'm not getting any errors today, so I can close the issue.

Would you have timestamps or more data on the failing requests for `rest1.biggestfan.net`? This is something @nicolaiskye and @nexerino might be interested in.

> What's wrong with BitcoreAPI? I'm not having any problems with it.

It has been very unreliable in the past. I haven't tried it recently, but we have a better solution now.

**Comment by merc1er** [comment]
#102 makes it more easy to customise API endpoints
