### ISSUE TITLE
message option (OP_RETURN) not working

### ISSUE THREAD

**Issue by LivioZ** [pybitcash/bitcash#104]
So I tried to send a transaction with optional message field, but without an address and/or with 0 value, there is an error, if I put an address and a value > 0 it goes on but the final transaction has not a OP_RETURN (obviously(?)). Thanks for helping.

**Comment by merc1er** [comment]
>  I tried to send a transaction with optional message field, but without an address and/or with 0 value

You cannot send a transaction without output or with 0 value.

>  if I put an address and a value > 0 it goes on but the final transaction has not a OP_RETURN 

Could you provide a minimal reproducible example?

Here is a code snippet that works as expected:

```python
from bitcash import Key


key = Key()
print(key.to_wif())
print(key.address)

key.get_balance()
key.send(
    [],
    leftover="bitcoincash:qrjluzvef02tz5czm5u90jkdalte8qldyqc7afjlsd",
    message="This was sent with BitCash"
)
```

**Comment by LivioZ** [comment]
Oh ok, thank you for that snippet, that's all I needed, I didn't know how to exactly put the parameters for an OP_RETURN transaction, maybe put this example in the docs?

**Comment by merc1er** [comment]
It should already be there as an example: https://pybitcash.github.io/bitcash/guide/advanced.html#blockchain-storage-op-return

**Comment by LivioZ** [comment]
Yea, but those 
`...` 
in 
`key.send(..., message='Simplicity level is over 9000!!!')` 
were not explicit enough for me.
