### ISSUE TITLE
How to sweep all BTC from wallet

### ISSUE THREAD

**Issue by enty8080** [pybitcash/bitcash#116]
Hi, @OverlordQ

Thanks for your library, but I have a question.

How to sweep/withdraw all BTC from BitCash wallet to custom address (another wallet, coinbase for instance)?

By sweeping I mean send every BTC and leave only that part which is needed for paying fee. Or if it is not possible, how to calculate the fee in order to know how much BTC I should leave for paying this fee?

Waiting for your reply,
Thanks

**Comment by merc1er** [comment]
BitCash only supports Bitcoin Cash (BCH). You will want to use `bit` for BTC.
