### ISSUE TITLE
Cash Tokens support CHIP-2022-02-CashTokens

### ISSUE THREAD

**Issue by damascene** [pybitcash/bitcash#121]
Would like to request support for Cash Tokens CHIP-2022-02-CashTokens

https://github.com/bitjson/cashtokens

**Comment by merc1er** [comment]
> Would like to request support for Cash Tokens CHIP-2022-02-CashTokens
> 
> 
> 
> https://github.com/bitjson/cashtokens

This change would be welcome!

Could you please submit a PR with cash tokens support?
