### ISSUE TITLE
wallet balance not accurate

### ISSUE THREAD

**Issue by joelinzy** [pybitcash/bitcash#123]
wallet balance not accurate.

seems to be from dependency on this service for the utxo information:
https://rest.bch.actorforth.org/v2/address/utxo

and the service is not showing accurate information (not synced).

here is an example:
https://blockchair.com/bitcoin-cash/outputs?q=recipient(qzxtfemsxz2qt4av3zj85qgtqa0vpd9sruqf99t9r3),is_spent(false)#

shows 4 utxos

https://rest.bch.actorforth.org/v2/address/utxo/qzxtfemsxz2qt4av3zj85qgtqa0vpd9sruqf99t9r3

shows 1 utxo.

see screenshots:
 
<img width="979" alt="Screenshot 2023-05-18 at 21 39 18" src="https://github.com/pybitcash/bitcash/assets/1952985/37a512af-b9e7-4867-b1dc-08311622c9f6">

<img width="1420" alt="Screenshot 2023-05-18 at 21 39 53" src="https://github.com/pybitcash/bitcash/assets/1952985/5550fd3b-d30b-4412-a488-8ae3f1e5918e">

**Comment by merc1er** [comment]
This should now be fixed.

https://rest.bch.actorforth.org/v2/address/utxo/qzxtfemsxz2qt4av3zj85qgtqa0vpd9sruqf99t9r3 now shows 4 UTXOs
