### ISSUE TITLE
Difference from `bit`

### ISSUE THREAD

**Issue by Danipulok** [pybitcash/bitcash#126]
Is there written anywhere what's all the differences between bitcash and bit?
I think it would be really nice to have a page in docs explaining this and what was changed \ improved.

**Comment by merc1er** [comment]
> Is there written anywhere what's all the differences between bitcash and bit?
> I think it would be really nice to have a page in docs explaining this and what was changed \ improved.

**BitCash** is for **Bitcoin Cash (BCH)**, while **Bit** is for **Bitcoin (BTC)**.

This is outlined on both the docs site and the repo:

> BitCash is Python’s [fastest](https://bitcash.dev/guide/intro.html#why-bitcash) Bitcoin Cash library

**Comment by merc1er** [comment]
If you are confused by what the differences between Bitcoin Cash and Bitcoin are, here's a comparison: https://whybitcoincash.com.

**Comment by Danipulok** [comment]
I mean difference between [bitcash](https://github.com/pybitcash/bitcash) and [bit](https://github.com/ofek/bit)

**Comment by merc1er** [comment]
This is what I explained just above:

BitCash and bit are for different cryptocurrencies/networks. A lot of the code is similar, as both networks are very similar, but they are incompatible.

The low level differences are those of the cryptocurrencies:
- BitCash has a different address format
- The third party API indexing transactions is that of the respective cryptocurrency

Some of the similarities are:
- How private keys are generated
- How public keys are derived

There are also changes over time as both libraries evolved in their own direction.

**Comment by Danipulok** [comment]
Oh, I finally got it. Thanks a lot for your time!
Appreciate a lot.
