### ISSUE TITLE
Cash address contains uppercase and lowercase characters

### ISSUE THREAD

**Issue by dinno-invis1ble** [pybitcash/bitcash#127]
I am unable to send BCH to standard P2PKH address.

It says "Cash address contains uppercase and lowercase characters", I read in documentation that bitcash supports Standard P2PKH transactions. How can I achieve this?

**Comment by merc1er** [comment]
> I am unable to send BCH to standard P2PKH address.
> 
> It says "Cash address contains uppercase and lowercase characters", I read in documentation that bitcash supports Standard P2PKH transactions. How can I achieve this?

I think BCH addresses only have lowercase characters. Could you send the address to confirm?

**Comment by dinno-invis1ble** [comment]
This is address I want to send funds: `1MTT8CrL9WPAeVJisRkTWvFCaAhGzzR4v2`

**Comment by merc1er** [comment]
> This is address I want to send funds: `1MTT8CrL9WPAeVJisRkTWvFCaAhGzzR4v2`

This is a BTC address. BitCash only support cashAddress format.
You can convert between the two formats there: https://bch.info/en/tools/cashaddr

**⚠️ Make sure you are sending to a BCH address ⚠️** The funds will likely be lost forever if you send to the wrong network.
