### ISSUE TITLE
How can you sign multiple inputs originating from various addresses?

### ISSUE THREAD

**Issue by dinno-invis1ble** [pybitcash/bitcash#131]
Hello,

Is there a method to sign multiple inputs that come from different addresses? I couldn't locate this information in the documentation.

Thank you in advance.

**Comment by merc1er** [comment]
If you build a transaction, that should give you a signed transaction with multiple unspents.

```python
from bit cash import Key


key = Key("...")

outputs = [("bitcoincash:qq2j4wmn285l38jem8ftfxnrv4ea5ljzrg6j37gmuj", 2000, "satoshi")]

unspents = key.get_unspents()
key.create_transaction(outputs, unspents=unspents)
# Returns: 0100000002bef932533cxxx0000
```

Does that answer the question?

**Comment by dinno-invis1ble** [comment]
What I'm trying to understand is how to consolidate funds from #address1 and #address2 in a single transaction. I've prepared the unspents, but how do I sign the transaction using both private keys?

**Comment by merc1er** [comment]
Sadly BitCash does not support HD wallets. So you can only send funds from a single address.

**Comment by dinno-invis1ble** [comment]
Thank you for assistance! 😄
