### ISSUE TITLE
How to send tx from P2PKH address to P2SH address? 

### ISSUE THREAD

**Issue by tracyspacy** [pybitcash/bitcash#27]

**Comment by teran-mckinney** [comment]
I don't think bitcash supports P2SH, even with the recent patches. bit supports P2SH now, as of very recently.

**Comment by tracyspacy** [comment]
> I don't think bitcash supports P2SH, even with the recent patches. bit supports P2SH now, as of very recently.
sad, do you plan to add P2SH support in near future? or could you recommend how can I do it myself?

**Comment by teran-mckinney** [comment]
I'd love to add it in but have no reason to work on it, myself.

I would look over bit's history and the recent commits here. It's a ton of complex work.

**Comment by zhtet036** [comment]
zhtett036agmail.com
