### ISSUE TITLE
Does it support SLP token?

### ISSUE THREAD

**Issue by Lafudoci** [pybitcash/bitcash#31]
I'm implementing BCH and SLP token into my tipperbot. The part of BCH was done with this nice lib. However, I didn't figure out the way to get balance and make transaction of SLP token with this lib. If it's possible, could you elaborate how to do it? Thank you.

**Comment by merc1er** [comment]
Bitcash doesn't seem to support SLP tokens at this point.

**Comment by teran-mckinney** [comment]
Not familiar with SLP tokens, personally. There were some patches added for some kind of token-esque support. I've been pretty out of the loop on these new developments. May want to look through the recent pull requests and see if something you need is in master. I haven't cut a new release in a while.

**Comment by libercash** [comment]
The first issue adding SLP tokens support is output order. By default, Bitcash adds first the standard outputs and then messages. According to SLP token specification, the first output should be a OP_RETURN. Additional OP_RETURN outputs in M position could be needed (i.e Mint baton). 

Changing sanitize_tx_data could be enough? The ideal could be passing an outputs list with mixed messages and P2PKH txs to create_transaction in the required order.

**Comment by teran-mckinney** [comment]
Possibly, I've yet to look into this or any OP_RETURNs.

**Comment by Lafudoci** [comment]
> The first issue adding SLP tokens support is output order. By default, Bitcash adds first the standard outputs and then messages. According to SLP token specification, the first output should be a OP_RETURN. Additional OP_RETURN outputs in M position could be needed (i.e Mint baton).
> 
> Changing sanitize_tx_data could be enough? The ideal could be passing an outputs list with mixed messages and P2PKH txs to create_transaction in the required order.

I have tried to build SLP tx manually but no success. It seems the issue is on the outputs order and SLP address recognizing. But I have not enough experience to imporve the code. Hope someone could help. SLP token is a promising feature to me.

**Comment by merc1er** [comment]
> SLP token is a promising feature to me.

I agree! 

I will try to look into the SLP spec and the transaction part of the code. If someone wants to help with building SLP transactions, that would be awesome as I can easily take care of the balance and broadcast part of it.

**Comment by merc1er** [comment]
This is being worked on 🚀

No ETA at this point, but a team of devs is looking into it.

**Comment by Lafudoci** [comment]
> This is being worked on 
> 
> No ETA at this point, but a team of devs is looking into it.

Hi, any update here? NFT becomes really hot now. I really need this cool thing!

**Comment by merc1er** [comment]
> > This is being worked on
> > No ETA at this point, but a team of devs is looking into it.
> 
> Hi, any update here? NFT becomes really hot now. I really need this cool thing!

maybe @nicolaiskye can give you an update on this

**Comment by merc1er** [comment]
No support at this point, this is being worked on but no ETA.
