### ISSUE TITLE
Search strings in OP_RETURN

### ISSUE THREAD

**Issue by libercash** [pybitcash/bitcash#39]
I think that providing a functionality to search strings inside op_return will be nice. 
Using fountainhead.cash (BitDB for BCH) makes it easy. 

I'm new to coding, but I've write a script to provide this functionality that could be later extended and even used for SLP tokens: 

[search.txt](https://github.com/sporestack/bitcash/files/3277638/search.txt)

What do you think? Also, I believe that some things here could be cleaned a little, like fees. 1 sat/B is enough for BCH so fee calculation is not an issue.

**Comment by teran-mckinney** [comment]
This is pretty cool. Unfortunately, haven't looked into SLP or done anything with OP_RETURN. I think someone else will have to chime in here.

**Comment by libercash** [comment]
I'll take a look at SLP tokens and try to integrate them in bitcash, although my technical knowledge is limited. Electron Cash SLP edition is written in Python, that's a good start.

**Comment by teran-mckinney** [comment]
Alright. I think there was some work done already on SLP, may want to look around the pull requests here. Might be worth pinging a few of the people already involved.

**Comment by merc1er** [comment]
Closing as SLP is now unused.
