### ISSUE TITLE
P2SH does not correspond to a mainnet nor testnet P2PKH address

### ISSUE THREAD

**Issue by Lafudoci** [pybitcash/bitcash#69]
When I tried to send BCH to this address:
`bitcoincash:pz5vmkpnxu7x4a5u9r0uftw0f42mqqxkgcjwwtjqgk`
I got this error: P2SH does not correspond to a mainnet nor testnet P2PKH address

It seems the issue is from that the API doesn't handle the P2SH script locking address well?

**Comment by teran-mckinney** [comment]
I don't think there's any P2SH support in bitcash. bit has it, though. Might be able to be ported over but yours is the first P2SH address I have seen.

**Comment by Lafudoci** [comment]
> I don't think there's any P2SH support in bitcash. bit has it, though. Might be able to be ported over but yours is the first P2SH address I have seen.

it sounds not easy to make it work. The address was from the BitoPro exchange.

**Comment by teran-mckinney** [comment]
Yeah, not simple at all. It was a lot of work on the bit branch. So some of the legwork is done, but it'd probably be pretty tough to port over.

I'm not sure how big Bitcoin Cash is on P2SH, might be worth investigating but I am busy with other things right now.

**Comment by merc1er** [comment]
> When I tried to send BCH to this address: `bitcoincash:pz5vmkpnxu7x4a5u9r0uftw0f42mqqxkgcjwwtjqgk` I got this error: P2SH does not correspond to a mainnet nor testnet P2PKH address
> 
> It seems the issue is from that the API doesn't handle the P2SH script locking address well?

This is now supported! Here's some money sent from BitCash: https://3xpl.com/bitcoin-cash/transaction/0c849243fc76a9d1bef526e5d8c85f18382a83b1014eb4c363ec1726685cd5fd

```py
key.send([("bitcoincash:pz5vmkpnxu7x4a5u9r0uftw0f42mqqxkgcjwwtjqgk", 1000, "satoshi")])
```
