### ISSUE TITLE
Testnet data isn't updated well

### ISSUE THREAD

**Issue by damascene** [pybitcash/bitcash#75]
I've noticed that testnet data isn't being updated and I get wrong results when I query for address balance or transactions.

I've compared the results with http://testnet.imaginary.cash/ data and I found that bitcash testnet data is not updated.

![image](https://user-images.githubusercontent.com/411046/93706043-2d46c680-fb2b-11ea-8c7c-74cc886d2630.png)

Would be useful to know sources or add more ones.

**Comment by teran-mckinney** [comment]
Agreed, the testnet API(s) might well be out of date.

**Comment by merc1er** [comment]
Seems like trest.bitcoin.com is no longer maintained.

Do you know alternatives? http://testnet.imaginary.cash/ seems to only be an explorer (also doesn't support HTTPS)

**Comment by merc1er** [comment]
I talked with the guys at https://cryptoapis.io but they only support calls with authentication. I think we want to avoid that ideally

**Comment by merc1er** [comment]
Both Bitcore and trest.bitcoin.com are unmaintained and highly unreliable.

Here are three options I am thinking about:
- change provider (not ideal)
- host our own infrastructure (I am looking into it for testnet)
- use a different way of communication with nodes (e.g. Fulcrum via sockets)

**Comment by teran-mckinney** [comment]
Do you think costs for hosting our own could be covered?

**Comment by merc1er** [comment]
That would be awesome. I also know a company that will deploy instances of rest.bitcoin.com to the public - not sure exactly when but they're working on it.

In the meantime I could run my own server - the testnet chain is apparently "only" 55 GB.

**Comment by teran-mckinney** [comment]
Will it run on a spinning disk or do we need a SSD?

**Comment by merc1er** [comment]
> Will it run on a spinning disk or do we need a SSD?

HDD is enough

**Comment by teran-mckinney** [comment]
What API would we run on it?

I see a $7/month server on OneProvider that could handle it.

**Comment by merc1er** [comment]
> What API would we run on it?
> 
> 
> 
> I see a $7/month server on OneProvider that could handle it.

With 60+ GB of storage? Also I haven't tried on testnet, but for mainnet you would need a better CPU and more RAM than what basic VPS usually offer.

**Comment by teran-mckinney** [comment]
Yeah, 128GB SSD or 1TB HDD.

I see, it may be the best way to go.

**Comment by merc1er** [comment]
I am setting up a local testnet node + rest API at https://trest.merc1er.com using [BCH-toolkit](https://github.com/actorforth/bch-toolkit).

It is harder than expected, Bitcoin.com closed source one of the key components, breaking most of the REST API's features 😅. But @actorforth have been working on a replacement that needs to be adjusted and should work just fine soon.

**Comment by teran-mckinney** [comment]
Ah, wow. Nice work!

**Comment by merc1er** [comment]
https://insomnia.fountainhead.cash - this is probably a better option

**Comment by teran-mckinney** [comment]
Great find. That is promising.

**Comment by merc1er** [comment]
> https://insomnia.fountainhead.cash - this is probably a better option

This does not seem to support testnet out of the box though

**Comment by merc1er** [comment]
> > https://insomnia.fountainhead.cash - this is probably a better option
> 
> This does not seem to support testnet out of the box though

It does have a server for testnet: https://insomnia-testnet.fountainhead.cash

**Comment by merc1er** [comment]
You can now customise the testnet endpoint with your own node running [BCH-toolkit](https://github.com/ActorForth/bch-toolkit) by setting the `BITCOINCOM_API_TESTNET` environment variable as per https://pybitcash.github.io/bitcash/guide/node.html.
