### ISSUE TITLE
Incorrect balances when calling key.get_balance('satoshi')

### ISSUE THREAD

**Issue by KenNewcomb** [pybitcash/bitcash#91]
Recently, the balances that I'm getting from key.get_balance() have been incorrect. Does anybody know what could be the issue?

Edit: Bitcoin.com may be having issues right now.

**Comment by merc1er** [comment]
Rest.bitcoin.com was down, and Bitcore is unreliable. 

We are working on replacing both APIs with our own infrastructure.

**Comment by merc1er** [comment]
This should now be resolved. If not, feel free to reopen the issue @KenNewcomb
