### ISSUE TITLE
Unable to sweep all the balance when more than 10 UTXOs

### ISSUE THREAD

**Issue by Lafudoci** [pybitcash/bitcash#95]
I have a function for moving all funds of an wallet to another wallet.
The code is following.
`key.send([], unspents=key.get_unspents(), leftover=receive_address)`

But it seems the max input counts was limited by 10 inputs. So it did not move all the balance.
https://explorer.bitcoin.com/bch/tx/09af7b957aa7c80cf9b06f71d7546752287bea0689008bd774160f3f9df086ce

How could I raise the limit? Or is there a better way to do the sweeping?

**Comment by teran-mckinney** [comment]
This is likely an issue with the API returning only ten unspents. What you're doing is fine.

I think @merc1er was looking into other APIs. It might fix this.

**Comment by merc1er** [comment]
All APIs are unreliable, and rest.bitcoin.com will be shut down very soon.

I am looking into a self hosted alternative but there are still some issues when running mainnet. I'll keep you updated.

**Comment by Lafudoci** [comment]
It seems they move endpoint to Fullstack.cash for increasing service stability. Could this endpoint be a drop-in-replacement for bitcash? At least for sort term. It's better to have a self-host option for long term.

**Comment by Lafudoci** [comment]
> This is likely an issue with the API returning only ten unspents. What you're doing is fine.

But I could get all unspents directly from the endopoint:
`https://rest.bitcoin.com/v2/address/utxo/qqmwupya3dm466q600xcxhunc766ucl3pszs3tsjsk`

That's why I wonder how were the inputs limited by 10 when sending tx with bitcash.

**Comment by merc1er** [comment]
> It seems they move [endpoint](https://rest.bitcoin.com/) to Fullstack.cash for increasing service stability. Could this endpoint be a drop-in-replacement for bitcash? At least for sort term. It's better to have a self-host option for long term.

Sadly not. Fullstack.cash is highly unreliable and most of the endpoints are different or return different data.

I should have a self-hosted instance of rest.bitcoin.com ready for use with BitCash in the coming days.

**Comment by Lafudoci** [comment]
@merc1er I applied #98 , but I still got no more than 10 outputs in transaction.
https://explorer.bitcoin.com/bch/tx/b074fec21b59c5afab0c9065ba2c72f0ac9cfdb652053555daf215fc7210781f

Does that mean the limitation was set in the lib? But I couldn't find it :(

**Comment by merc1er** [comment]
@Lafudoci could you share a code snippet so that I can reproduce?

**Comment by Lafudoci** [comment]
> @Lafudoci could you share a code snippet so that I can reproduce?

Sure, here is my code
```
tx_result = key.send([], unspents=key.get_unspents(), leftover=receive_address)
log.info('TX result:'+str(tx_result))
if type(tx_result) == str and len(tx_result) == 64:
    return tx_result
else:
    return -1
```

**Comment by merc1er** [comment]
This worked perfectly fine for me:

```python
In [1]: from bitcash import Key

In [2]: k = Key("KxWsUecxYTgLnkhU47iVZydJipX3gXU3Y6DH74EdpSKaaA1K4uuF")

In [3]: u = k.get_unspents()

In [4]: u
Out[4]: 
[Unspent(amount=1085, confirmations=0, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='b2ce20150826365f762003aa707da7a6aba957525215239417706466d4eb51e1', txindex=0),
 Unspent(amount=1085, confirmations=0, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='94e19e04e1a4520895d44f91a316c7c476ad7fe686a758d10977e6ea9ee1a13c', txindex=0),
 Unspent(amount=1085, confirmations=0, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='d103c6ecc19964bf0c8f78befaad77591604a77882ea52920a6fcadcd0447776', txindex=0),
 Unspent(amount=1085, confirmations=0, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='ef18548d810bd05ea5694f74cd84156e8797a5bf387945e330594c12999f83fd', txindex=0),
 Unspent(amount=1085, confirmations=0, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='cd75bbae4b5af658cdc1e4195b4441c1af6fde67ee7976c8fe3a71b02699a8d2', txindex=0),
 Unspent(amount=1085, confirmations=0, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='f433a9896981f339876c163e7174a21c83b6f2498cee7c11e1b691e8e32dd0ad', txindex=0),
 Unspent(amount=1085, confirmations=2, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='11616c5c53f969a4f4d60c15c4289d32c0438cfc1c38f3b175ac04e791fb37dc', txindex=0),
 Unspent(amount=1084, confirmations=2, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='ed5e7710c257c01ae5967ed58d2cf8c1c3688798931594da860755486310205f', txindex=0),
 Unspent(amount=1084, confirmations=2, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='fa532dde3c237bfeb982a743886b6f351376f56707b7b7606592aef5560b040d', txindex=0),
 Unspent(amount=1084, confirmations=2, script='76a91427faca1420a19d75311ea3b6c20551d9e245896988ac', txid='81212c1096cff2dbcf62d9612e6abcfdc458168c916904e9748ceff81dc6387f', txindex=0)]

In [8]: len(k.get_unspents())
Out[8]: 12

In [9]: k.send([], leftover="bitcoincash:qzqg03jqnvespwzvfjqd7hxfscdsmkzwzsqdtnyhwd")
Out[9]: '1513900ef6b2d7b721cabe3f127273810753c2b62911c56802d7bff07008da01'

In [10]: k.get_unspents()
Out[10]: []
```

**Comment by merc1er** [comment]
Please provide with a fully reproducible code snippet @Lafudoci, including private key with prepared UTXOs (testnet or you can DM it to me if you prefer: same username on Twitter and Telegram).

Closing this for now.

**Comment by Lafudoci** [comment]
I think I figured out. Previous the bitcoin com API only return 10 outputs sometimes(maybe due to server resource loading-balance), so I could only sent 10 max UTXO. Not sure if the new API biggestfan follows the same behavior?

Then lately I got exception ConnectionError. It's actually a HTTP code 413 (Payload Too Large) by trying to use complete unspents list to send raw transaction. So it seems the bottleneck is at API limit.

So my solution is to split the unspents into several transaction by 20-ish unspents chunk. And that works fine to me.

**Comment by merc1er** [comment]
> So my solution is to split the unspents into several transaction by 20-ish unspents chunk. And that works fine to me.

Great! So does that mean it worked with version `0.6.3`?

**Comment by Lafudoci** [comment]
> > So my solution is to split the unspents into several transaction by 20-ish unspents chunk. And that works fine to me.
> 
> Great! So does that mean it worked with version `0.6.3`?

Oh, I was using 0.6.2, and now I don't have huge-unspent wallet for testing on 0.6.3.

**Comment by merc1er** [comment]
0.6.3 uses the biggest fan endpoint. So the UTXO issue should be solved but probably not the large payload one.

**Comment by Lafudoci** [comment]
I'm going to close this since the large payload issue was not actually related to bitcash. And the API stability should have resolved by changing endpoint. Thank you.
